filecloud/config/routes.rb
Filecloud::Application.routes.draw do

  resources :password_resets
  resources :users
  root to: 'homes#home'
  match '/activate',to: 'users#activate'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/filestreams/multiple_delete', to: 'filestreams#multiple_delete'
  match '/folders/create_child', to: 'folders#create_child', via: :post
  match '/filestreams/password_protect', to: 'filestreams#password_protect', via: :post
  match '/filestreams/create_unlocked', to: 'filestreams#create_unlocked', via: :post
   match '/filestreams/download', to: 'filestreams#download', via: :post
   match '/filestreams/move_file', to: 'filestreams#move_file', via: :post
   match '/filestreams/rename', to: 'filestreams#rename', via: :post
   match '/filestreams/facebook', to: 'filestreams#facebook', via: :post
   match '/filestreams/:id', to: 'filestreams#show', via: :post

  resources :categories

  resources :folders do
  	member do
  		get 'share_file'
  	end
  	member do
  		get 'folder_download'
  	end
  	member do
  		get 'folder_child'
  	end
    member do
        get 'accept'
    end
    collection do
        get 'indexpublic'
    end
  end

  resources :foldersharings
  resources :filesharings do
  	member do
   		get 'share_file'
    end
  end

  resources :filestreams do
    member do
      get 'download_public_file'
    end
    member do
      get 'delete_from_folder'
    end
     member do
        get 'accept'
    end
    collection do
        get 'indexpublic'
    end
    collection do
      get 'editcontent'
    end

  end

end

filecloud/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

filecloud/app/views/shared/_footer.html.erb
<div id="footer">
  <p class="footer">
    <a href="http://filecloud.jp/">Filecloud</a> is released under the 
  </p>
</div>

filecloud/app/views/shared/_header.html.erb
<div id="header">
  <% if signed_in? -%>
  <div class="user_welcome">
    <p>
      <%= t :hello %>, <%= current_user.name %>!<br/>
      <%= link_to t(:settings), edit_user_path(current_user) %> | <%= link_to t(:sign_out), signout_path, :method => :delete %>
    </p>
  </div>
  <% end -%>
  <%= link_to image_tag('logo.png', :alt => 'Boxroom'), root_path %>
</div>

filecloud/app/views/shared/_menu.html.erb
<div id="menu">
  <p class="menu">
    <% if signed_in? -%>
      <%= link_to t(:folders), folders_path %> &nbsp; &nbsp;
      <%= link_to "Category", categories_path %> &nbsp; &nbsp;
      <%= link_to t(:shared_files), share_links_path %>&nbsp;&nbsp;
      <% if current_user.member_of_admins? -%>
        <%= link_to t(:users), users_path %> &nbsp; &nbsp;
        <%= link_to t(:groups), groups_path %> &nbsp; &nbsp;

      <% end -%>
    <% end -%>
    &nbsp;
  </p>
</div>

filecloud/app/views/shared/notify.html.erb
<div >
<h1 style="color:red"> Not found </h1>
<div>