filecloud/config/routes.rb
Filecloud::Application.routes.draw do

  resources :password_resets
  resources :users
  root to: 'homes#home'
  match '/activate',to: 'users#activate'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/filestreams/multiple_delete', to: 'filestreams#multiple_delete'
  match '/folders/create_child', to: 'folders#create_child', via: :post
  match '/filestreams/password_protect', to: 'filestreams#password_protect', via: :post
  match '/filestreams/create_unlocked', to: 'filestreams#create_unlocked', via: :post
   match '/filestreams/download', to: 'filestreams#download', via: :post
   match '/filestreams/move_file', to: 'filestreams#move_file', via: :post
   match '/filestreams/rename', to: 'filestreams#rename', via: :post
   match '/filestreams/facebook', to: 'filestreams#facebook', via: :post
   match '/filestreams/:id', to: 'filestreams#show', via: :post

  resources :categories

  resources :folders do
  	member do
  		get 'share_file'
  	end
  	member do
  		get 'folder_download'
  	end
  	member do
  		get 'folder_child'
  	end
    member do
        get 'accept'
    end
    collection do
        get 'indexpublic'
    end
  end

  resources :foldersharings
  resources :filesharings do
  	member do
   		get 'share_file'
    end
  end

  resources :filestreams do
    member do
      get 'download_public_file'
    end
    member do
      get 'delete_from_folder'
    end
     member do
        get 'accept'
    end
    collection do
        get 'indexpublic'
    end
    collection do
      get 'editcontent'
    end

  end

end

filecloud/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :login, :name, :password, :password_confirmation,:status, :password_reset_token,
   :password_reset_sent_at, :admin, :created_at, :updated_at, :password_digest, :remember_token,
   :avatar
  has_many :folders
  has_attached_file :avatar, :styles => { :medium => "240x150>", :thumb => "100x100>" }
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  has_many :filesharings, foreign_key: "shared_user_id", class_name: "Filesharing", dependent: :destroy
  has_many :foldersharing, foreign_key: "shared_user_id", class_name: "Foldersharing", dependent: :destroy
  has_secure_password
  validates :name, presence: true, length: { maximum: 50 }
  validates :password,
            :presence => true,
            :confirmation => true,
            :length       => { :minimum => 6 },
            :if => lambda{ new_record? || !password.nil? },
            :on => :create
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

   def send_password_reset
      self.password_reset_token=SecureRandom.urlsafe_base64
      self.password_reset_sent_at = Time.zone.now
      save!(:validate => false)
      UserMailer.delay({:run_at => 10.seconds.from_now}).password_reset(self)
    end

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

    def self.search(search)
      if search
        find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
      else
        find(:all)
      end
    end
end

filecloud/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy, :show]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy
  # before_filter :set_mailer_host
  # before_filter :set_host_from_request, only: [:create]

  def index
    # @user_name = User.find_by_sql(["Select name from users"])
    @users = User.search(params[:search])
    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @users }
    # end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

	def create
    @user = User.new(params[:user])
    @code = SecureRandom.urlsafe_base64
    @user.login=@code
    if @user.save
      UserMailer.delay.welcome_email(@user)
      flash[:success] = "Welcome to the Sample App! Please in your mail activate account"
      render 'sessions/new'
    else
      render 'new'
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def activate
    @user=User.find(params[:id])
    if @user.login == params[:active_code]
      if @user.status != true
        if @user.update_attribute(:status, true)
      	  flash[:success] = "Welcome to the Sample App"
          render 'sessions/new'
        else
          flash[:success] = "Please activate in your mail"
          render 'sessions/new'
        end
      else
        signed_in_user
      end
   	else
      flash[:error] = "Error!!!"
      render 'sessions/new'
    end
  end

  private
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end



end

filecloud/app/helpers/users_helper.rb
module UsersHelper
  def user_belongs_to_group(group)
    unless @user.nil?
      @user.groups.include?(group)
    end
  end
end

filecloud/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <% unless @user.new_record? -%>
    <p>User Avatar<br/>
      <%= image_tag @user.pic.url(:thumb) %>
      <br/><br/>
      <%= f.file_field :pic %>
    </p>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name, { :class => 'text_input' } %>
    </p>
  <% end -%>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email, { :class => 'text_input' } %>
  </p>
  <% unless @user.new_record? -%>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password, { :class => 'text_input' } %>
    </p>
    <p>
      <%= label_tag t(:confirm_password) %>
      <%= f.password_field :password_confirmation, { :class => 'text_input' } %>
    </p>
  <% end -%>
  <% if signed_in? && current_user.member_of_admins? -%>
    <p>
      <%= t :member_of_these_groups %>:
      <span class="user_groups">
        <% Group.all.each do |group| -%>
          <% if @user.is_admin && group.admins_group? -%>
            <span class="group nowrap disabled">
              <input type="checkbox" checked="checked" disabled="disabled" />
              <%= group.name %>
            </span>
          <% else -%>
            <span class="group nowrap">
              <%= check_box_tag('user[group_ids][]', group.id, user_belongs_to_group(group)) %>
              <%= group.name %>
            </span>
          <% end -%>
        <% end -%>
      </span>
    </p>
  <% end -%>
  <p>
    <%= f.submit t(:save) %>
    <% if @user != current_user -%>
      &nbsp; &mdash; &nbsp;
      <%= link_to t(:back), users_url %>
    <% end -%>
  </p>
<% end %>

filecloud/app/views/users/_show.html.erb
<p id="notice"><%= notice %></p>
<h1>User Information</h1>
<p>
  <b>Avatar:</b>
  <% if @current_user.avatar.url.include? "missing.png" %>
   <%= image_tag("default_avatar.gif")  %>
  <%else%>
    <%= image_tag @current_user.avatar.url(:medium) %>
  <%end%>
</p>
  <b>Name:</b>
  <%= @current_user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @current_user.email %>
</p>
<p>
	<b>List folders: </b><br/>

	<% @current_user.folders.each do |folder|%>
		<% if Folder.where(:user_id => current_user, :id => folder.id).exists? %>
			<a href="/folders/<%=folder.id%>"><%= folder.name%></a><br/>
		<% end %>
	<% end %>
</p>

<p>
	<% @lists = Foldersharing.where(:shared_user_id => current_user) %>
	<b>List folders are shared by other members : </b><br/>
	<table class="table table-hover">

		<tr>
			<th>Folder name</th>
			<th>Share by</th>
			<th>Time</th>
		</tr>
		<% @lists.each do |list|%>
		<tr>
		<td><a href="/folders/<%=list.folder_id%>"><%= Folder.find(list.folder_id).name %></a></td>
		<td><%=User.find(Folder.find(list.folder_id).user_id).name%> (<%=User.find(Folder.find(list.folder_id).user_id).email%>)</td>
		<td><%= Foldersharing.find(list.id).created_at.strftime("%m/%d/%Y") %></td>
		</tr>
	<% end %>
		</table>
</p>	<br/>
<p><b>List files are shared by others members: </b><br/>

	<table class="table table-hover">
		<tr>
			<th>File name</th>
			<th>View file (image only)</th>
			<th>Download</th>
			<th>Share by</th>
			<th>Time</th>
		</tr>
	 	  <% listFiles = Filesharing.where(:shared_user_id => current_user) %>
		  <% listFiles.each do |file|%>
				  <td><%= Filestream.find(file.file_id).attach_file_name %></td>

				<% if Filestream.find(file.file_id).attach_content_type.include? "image"%>
				 <td>
					<span><a href="#previewModal-<%=file.file_id%>" data-toggle="modal"><%= image_tag("preview.jpeg",:size => "30x30", alt: "Preview") %></a></span>

				<div id="previewModal-<%=file.file_id%>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="previewModalLabel" aria-hidden="true" data>
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h3 id="previewModalLabel"><%=Filestream.find(file.file_id).attach_file_name%></h3>
					</div>
				<div class="modal-body">
					<%= image_tag Filestream.find(file.file_id).attach.url %>
				</div>
				<div class="modal-footer">
						<button type="button" class="btn btn-large" onClick="location.href='/filestreams/<%=file.file_id%>/download_public_file'"><i class="icon-download icon-white"></i>Download</button>
					</div>
				</div>
				</td>
				<%else%>
					<td></td>
				<%end%>
			<td><%= link_to 'Download', download_public_file_filestream_path(file.file_id) %></td>
			<td><%= User.find(Folder.find(Filestream.find(file.file_id).folder_id).user_id).name %> (<%= User.find(Folder.find(Filestream.find(file.file_id).folder_id).user_id).email %>)</td>
				<td><%= Filesharing.find_by_file_id(file.file_id).created_at.strftime("%m/%d/%Y") %></td>
		<tr>
		</tr>
		<% end %>
	</table>
</p>



<br/><br/><br/><br/>
<%= link_to 'Edit', edit_user_path(current_user) %> |
<%= link_to 'Back', users_path %>
<br></br>

filecloud/app/views/users/_users.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="tblUsers">
  <tr>
    <th><%= sortable "name" %></th>
    <th><%= sortable "email" %></th>
    <th>Login</th>
    <% if current_user.admin?%>
        <th colspan=3>Action</th>
    <%else%>
        <th colspan=2>Action</th>
    <%end%>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.login %></td>
    <td><%= link_to image_tag("info.png", alt: "Show"), user %></td>
    <% if current_user?(user) %>
        <td><%= link_to image_tag("edit.png", alt: "Edit"), edit_user_path(user) %></td>
    <%else%>
        <td>&nbsp</td>
    <% end %>
    <% if current_user.admin? %>
        <% if current_user!=user%>
          <td>
            <%= link_to image_tag("del.png", alt: "delete"), user, method: :delete,
                                    data: { confirm: "You sure?" } %>
          </td>
        <%else%>
          <td>&nbsp</td>
        <%end%>  
    <%end%>
  </tr>
<% end %>
</table>

filecloud/app/views/users/index.html.erb
<% provide(:title, 'Listing User') %>
<h1>Listing users</h1>
<%= form_tag users_path, :method => 'get', :id => "users_search" do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil %>
	</p>
	<div class="listUser">
		<%= render 'users' %>
	</div>
<% end %>

<br />
<% if current_user.admin? %>
	<%= link_to 'New User', new_user_path ,class: "btn btn-large btn-primary"%>
<%end%>
<%= will_paginate %>

filecloud/app/views/users/index.js.erb
$('#abc').html('<%= escape_javascript(render("users")) %>');

filecloud/app/views/users/listuser.html.erb
<!-- list user -->
<div class="span11">
  <legend style="margin-top:30px">List all user</legend>
  <table class="table table-hover">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="2" text-align="center">Action</th>

    </tr>
    <% if !@users.nil? %>

      <% @users.each do |us| %>
        <tr>
          <td><%= us.name %></td>
          <td><%= us.email %></td>
          <td>
            <a href="/users/<%= us.id%>/update_role">Update info</a>

          </td>
          <td>

            <%= link_to "Destroy", user_path(us.id), :data => { :confirm => "Are you sure?" }, :method => :delete %>
          </td>
          <td></td>
        </tr>
      <% end %>
      <%= will_paginate%>
    <%end  %>
  </table>
</div>

<!--ket thuc-->

filecloud/app/views/users/new.html.erb
<% content_for :title, t(:new_user) -%>

<h1><%= content_for :title %></h1>
<%= render 'form' %>

filecloud/app/views/users/register.html.erb
<p>Welcome <%= @resource.email %>!</p>

<p>We're pleased to invite you to try <%= link_to 'filecloud.com', root_url %>.</p>

<p>Please click the link below to confirm your email address and set your password:</p>

<p><%= link_to 'Confirm my account', confirmation_url(@resource, :confirmation_token => @resource.confirmation_token) %></p>

filecloud/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1>User Information</h1>
<p>
  <b>Avatar:</b>
  <% if @user.avatar.url.include? "missing.png" %>
   <%= image_tag("default_avatar.gif")  %>
  <%else%>
    <%= image_tag @user.avatar.url(:medium) %>
  <%end%>
</p>
<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>
<p>

	<b>List folders: </b><br/>
	<% @user.folders.each do |folder|%>
		<% if Folder.where(:user_id => current_user, :id => folder.id).exists? %>
			<a href="/folders/<%=folder.id%>"><%= folder.name%></a><br/>
		<% end %>
	<% end %>
</p>
<% if signed_in? %>
<% if current_user.id == params[:id].to_i %>
<p>
	<% @lists = Foldersharing.where(:shared_user_id => current_user) %>
	<b>List folders are shared by other members : </b><br/>
	<table class="table table-hover">

		<tr>
			<th>Folder name</th>
			<th>Share by</th>
			<th>Time</th>
		</tr>
			<% @lists.each do |list|%>
		<tr>
		<td><a href="/folders/<%=list.folder_id%>"><%= Folder.find(list.folder_id).name %></a></td>
		<td><%=User.find(Folder.find(list.folder_id).user_id).name%> (<%=User.find(Folder.find(list.folder_id).user_id).email%>)</td>
		<td><%= Foldersharing.find(list.id).created_at.strftime("%m/%d/%Y") %></td>
		</tr>
	<% end %>
		</table>
</p>	<br/>
<p><b>List files are shared by others members: </b><br/>

    <table class="table table-hover">
    	<tr>
				<th>File name</th>
				<th>View file (image only)</th>
				<th>Download</th>
				<th>Share by</th>
				<th>Time</th>
			</tr>
		 	  <% listFiles = Filesharing.where(:shared_user_id => current_user) %>
		    <% listFiles.each do |file|%>
				  <td><%= Filestream.find(file.file_id).attach_file_name %></td>
					  <% if Filestream.find(file.file_id).attach_content_type.include? "image"%>
				   <td>
					<span><a href="#previewModal-<%=file.file_id%>" data-toggle="modal"><%= image_tag("preview.jpeg",:size => "30x30", alt: "Preview") %></a></span>

				<div id="previewModal-<%=file.file_id%>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="previewModalLabel" aria-hidden="true" data>
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h3 id="previewModalLabel"><%=Filestream.find(file.file_id).attach_file_name%></h3>
					</div>
					<div class="modal-body">
							<%= image_tag Filestream.find(file.file_id).attach.url %>
					</div>
				<div class="modal-footer">
						<button type="button" class="btn btn-large" onClick="location.href='/filestreams/<%=file.file_id%>/download_public_file'"><i class="icon-download icon-white"></i>Download</button>
					</div>
				</div>
				</td>
					<%else%>
						<td></td>
					<%end%>
				<td><%= link_to 'Download', download_public_file_filestream_path(file.file_id) %></td>
				<td><%= User.find(Folder.find(Filestream.find(file.file_id).folder_id).user_id).name %> (<%= User.find(Folder.find(Filestream.find(file.file_id).folder_id).user_id).email %>)</td>
				<td><%= Filesharing.find_by_file_id(file.file_id).created_at.strftime("%m/%d/%Y") %></td>
			<tr>
			</tr>
			<% end %>
    </table>
</p>
		<% end %><% end %>
		<% if signed_in? %>
		<% if current_user.id == params[:id].to_i %>
		<%= link_to 'Edit', edit_user_path(@user) %> |
		<% end %><% end %>
		<%= link_to 'Back', users_path %>
<br></br>

filecloud/app/views/users/update_role.html.erb
<!-- form edit -->
<div class="row ">
  <%= form_for(@user) do |f| %>
    <div class="span6 fom-inline offset4">
      <div class="span2">
        <%= f.label :name %>
      </div>
      <div class="span3">
        <%= f.text_field :name %>
      </div>

      <div class="span2"><%= f.submit (@user.id.nil?)?  t('system.btn_save') :
          t('system.btn_update'), class: "btn  btn-primary" %></div>

        <% end %>
      </div>

    </div>
    <!-- ket thuc-->