filecloud/config/routes.rb
Filecloud::Application.routes.draw do

  resources :password_resets
  resources :users
  root to: 'homes#home'
  match '/activate',to: 'users#activate'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/filestreams/multiple_delete', to: 'filestreams#multiple_delete'
  match '/folders/create_child', to: 'folders#create_child', via: :post
  match '/filestreams/password_protect', to: 'filestreams#password_protect', via: :post
  match '/filestreams/create_unlocked', to: 'filestreams#create_unlocked', via: :post
   match '/filestreams/download', to: 'filestreams#download', via: :post
   match '/filestreams/move_file', to: 'filestreams#move_file', via: :post
   match '/filestreams/rename', to: 'filestreams#rename', via: :post
   match '/filestreams/facebook', to: 'filestreams#facebook', via: :post
   match '/filestreams/:id', to: 'filestreams#show', via: :post

  resources :categories

  resources :folders do
  	member do
  		get 'share_file'
  	end
  	member do
  		get 'folder_download'
  	end
  	member do
  		get 'folder_child'
  	end
    member do
        get 'accept'
    end
    collection do
        get 'indexpublic'
    end
  end

  resources :foldersharings
  resources :filesharings do
  	member do
   		get 'share_file'
    end
  end

  resources :filestreams do
    member do
      get 'download_public_file'
    end
    member do
      get 'delete_from_folder'
    end
     member do
        get 'accept'
    end
    collection do
        get 'indexpublic'
    end
    collection do
      get 'editcontent'
    end

  end

end

filecloud/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
    <% if signed_in? %>
	    <a href="/users/<%=current_user.id%>" id="logo">FileCloud Project</a>
    <%else%>
      <%= link_to "Training Project", root_path, id: "logo" %>
    <% end %>
      <nav>
        <ul class="nav pull-right">
        	<li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Public<b class="caret"></b>
</a>
              <ul class="dropdown-menu">
                <li><a href="/folders/indexpublic">Public folders</a></li>
                <li class="divider"></li>
                <li><a href="/filestreams/indexpublic">Public files</a></li>
              </ul>
          </li>
          <% if signed_in? %>
          <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Categories", categories_path %></li>
            <li><%= link_to "My folders", folders_path%></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %><b class="caret"></b>
              </a>
                <ul class="dropdown-menu">
                   <li><a href="/users/<%=current_user.id%>/edit"> Edit profile</a></li>
                   <li class="divider"></li>
                   <li><a href="/signout" data-method="delete" >SignOut</a></li>
                </ul>
            </li>
              <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

filecloud/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div style="width:834px;" class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

filecloud/app/views/layouts/_navigation.html.erb
  <ul id="nav">
    <% if user_signed_in? %>
      <li style="color:red;margin-top:19px;">Hello <%=current_user.email%></li>
      <li>
        <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
      </li>
    <% else %>
      <li>
        <%= link_to 'Login', new_user_session_path %>
      </li>
    <% end %>
    <% if user_signed_in? %>
      <li>
        <%= link_to 'Edit profile', edit_user_registration_path %>
      </li>
      <li>
        <%= link_to 'Folders ', folders_path %>
      </li>
      
      <li>
         <%= link_to 'Categories', categories_path %>
      </li>
      <% if current_user.has_role? :admin %>
        <li>
          <%= link_to 'Users', users_path %>
        </li>
        <li style="display: none;">
          <%= link_to 'Roles', roles_path %>
        </li>
      <% end %>
    <% else %>
      <li>
        <%= link_to 'Sign up', new_user_registration_path %>
      </li>
    <% end %>
  </ul>

filecloud/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Filecloud</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container" >
	    <% flash.each do |key, value| %>
	      <div class="alert alert-<%= key %>"><%= value %></div>
	    <% end %>
	    <%= yield %>
	    <%= render 'layouts/footer' %>
		</div>
	</body>

</html>