filecloud/config/routes.rb
Filecloud::Application.routes.draw do

  resources :password_resets
  resources :users
  root to: 'homes#home'
  match '/activate',to: 'users#activate'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/filestreams/multiple_delete', to: 'filestreams#multiple_delete'
  match '/folders/create_child', to: 'folders#create_child', via: :post
  match '/filestreams/password_protect', to: 'filestreams#password_protect', via: :post
  match '/filestreams/create_unlocked', to: 'filestreams#create_unlocked', via: :post
   match '/filestreams/download', to: 'filestreams#download', via: :post
   match '/filestreams/move_file', to: 'filestreams#move_file', via: :post
   match '/filestreams/rename', to: 'filestreams#rename', via: :post
   match '/filestreams/facebook', to: 'filestreams#facebook', via: :post
   match '/filestreams/:id', to: 'filestreams#show', via: :post

  resources :categories

  resources :folders do
  	member do
  		get 'share_file'
  	end
  	member do
  		get 'folder_download'
  	end
  	member do
  		get 'folder_child'
  	end
    member do
        get 'accept'
    end
    collection do
        get 'indexpublic'
    end
  end

  resources :foldersharings
  resources :filesharings do
  	member do
   		get 'share_file'
    end
  end

  resources :filestreams do
    member do
      get 'download_public_file'
    end
    member do
      get 'delete_from_folder'
    end
     member do
        get 'accept'
    end
    collection do
        get 'indexpublic'
    end
    collection do
      get 'editcontent'
    end

  end

end

filecloud/app/models/category.rb
class Category < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name
  attr_accessible :description, :name
  has_many :folders,class_name: "Folder", foreign_key: "category_id", dependent: :destroy
  validates :name, :presence => true, :uniqueness => true
  validates :description, :presence => true



def self.search(search)
  if search
    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end


  # def to_s
  #   self.name
  # end
end

filecloud/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :signed_in_user

  def index
    @search = Category.search(params[:search])
   	if ( @new_category.nil?)
	  	@new_category = Category.new
		end
    respond_to do |format|
      format.html { render action: "index"}
      format.js {render js: @search }
    end
	end

	def new
	  @new_category = Category.new
	end

	def create

	  @new_category = Category.new(params[:category])
		respond_to do |format|
		  if @new_category.save
        @new_category = nil
        @search = Category.search(params[:search])
     	  format.html { render action: "index"}
        format.js {render js: @new_category }
        format.js {render js: @search }
      else
				@search = Category.search(params[:search])
        format.html { render action: "index"}
        format.js {render js: @new_category.errors, status: :unprocessable_entity}
        format.js {render js: @search }
	    end
    end
	end

	def show
	  @category = Category.find(params[:id])
		@folders = Folder.where(:category_id => params[:id],:user_id => current_user.id)
 	  respond_to do |format|
    	format.html { render action: "show"}
    	format.js {render js: @category }
    end
	end

	def edit
		@search = Category.search(params[:search])
   	@new_category = Category.find(params[:id])
		respond_to do |format|
		  format.html { render action: "index"}
		  format.js {render js: @new_category}
		  format.js {render js: @search }
		end
	end

	def update
		@new_category = Category.find(params[:id])
	  respond_to do |format|
	    if @new_category.update_attributes(params[:category])
			  @new_category = nil
			  @search = Category.search(params[:search])
        format.html {  render action: "index"}
        format.js { render js: @new_category }
        format.js { render js: @search }
		  else
		  	@search = Category.search(params[:search])
        format.html {  render action: "index"}
        format.js {render js: @new_category.errors, status: :unprocessable_entity}
        format.js { render js: @search }
      end
    end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		respond_to do |format|
		   format.html {  render action: "index"}
		end
	end

end

filecloud/app/helpers/categories_helper.rb
module CategoriesHelper
end

filecloud/app/views/categories/_categories.html.erb
	<div class="span2">
		<%= f.label :name %>
	</div>
  <div class="span3">
    <%= f.text_field :name %>
  </div>
  <div class="span2">
  	<%= f.label :description %>
  </div>
  <div class="span3">
    <%= f.text_area :description, :size => "20x4" %>
  </div>
	</br>

filecloud/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

filecloud/app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

filecloud/app/views/categories/index.html.erb
<h1>Categories management</h1>

<%= form_tag categories_path, :method => :get do %>
  <p class="span2">

    <label style="float:left;">Category Name </label>

    	<%= text_field_tag :search, params[:search], class: "tf-search" %>
    <%= submit_tag "Search", :name => nil , class: "btn  btn-primary" %>
  </p>
<% end %>

<br></br><br></br>

	<div class="row">
		<%
		  if(@new_category.nil?)
		    @new_category= Category.new
		  end
		%>
		<%= form_for(@new_category) do |f| %>
			<div class="span7">
				<h2>New category</h2>
					<%= render 'shared/error_messages', object: f.object %>
					<%= render 'categories',st: @new_category , f: f%>
					<div class="span4">
						</br>
							<%= f.submit  class: "btn  btn-primary"%>
						</div>
		  </div>
		<%end%>
	</div>

	<div class="span8">
		<table class="table table-hover">
			<br/>
		  <tr>
				<th>Name</th>
				<th>Description </th>
				<th>Show Details</th>
				<th> Edit </th>
			</tr>
		  <%if !@search.nil? %>
		  	<% @search.each do |category|%>
					<tr>
						<td><%= category.name %> </td>
						<td><%= category.description %></td>
						<td><%= link_to 'Show', category_path(category)%></td>
						<td><%= link_to 'Edit', edit_category_path(category) %></td>
					</tr>
		    <% end %>
		  <% end %>
		</table>
	</div>
</div>

<style type="text/css">
input.tf-search{
	width: 200px;
	float: left;
	margin-left: 10px;
	margin-right: 10px;
}
p.span2{
	width: 400px;

}
</style>

filecloud/app/views/categories/new.html.erb
<h1>New category</h1>

<!-- <%= render 'form' %> -->

<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Category'%>
  </div>
<% end %>


<%= link_to 'Back', categories_path %>

filecloud/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<%if @category.folders.blank?%>
	<legend>These is Files not contian in this category</legend>
<%else%>
	<legend>These is Files contian in this category</legend>
<%end%>
<table class="table table-bordered">
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th colspan="2" style="text-align:center">Name folder</th>
	</tr>
	
		<tr>
			<td><%= @category.name %></td>
			<td><%= @category.description %></td>
			<% @category.folders.each do |f| %>
				<td><%= link_to f.name, {:action=>'show',:controller=>'folders',:id=>f.id},{:method=>'get'} %></td>
			<% end %>	
		</tr>
	
</table>

<%= link_to 'Back', categories_path %>